name = "unitycup"
compatibility_date = "2024-03-20"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "unitycup-db"
database_id = "ce571f08-94ba-44b8-aad6-cda0e431739f"
migrations_dir = "drizzle"
